apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server.monitoring.svc.cluster.local
        isDefault: true
        editable: false
        jsonData:
          timeInterval: "15s"
          queryTimeout: "30s"
          httpMethod: "POST"
          manageAlerts: true
      - name: Loki
        type: loki
        access: proxy
        url: http://loki-gateway.monitoring.svc.cluster.local
        jsonData:
          maxLines: 1000
          timeout: 30
      - name: SecurityMetrics
        type: prometheus
        access: proxy
        url: http://security-metrics-service.monitoring.svc.cluster.local:9090
        database: security_metrics
        jsonData:
          timeInterval: "30s"
          queryTimeout: "60s"
          httpMethod: "POST"