apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-alerts
  namespace: monitoring
data:
  alerts.yaml: |
    groups:
      - name: SecurityAlerts
        rules:
        - alert: HighVulnerabilityCount
          expr: security_vulnerabilities_total > 10
          for: 5m
          labels:
            severity: critical
            category: security
          annotations:
            summary: High number of security vulnerabilities detected
            description: More than 10 security vulnerabilities have been detected in the last scan

        - alert: PipelineFailure
          expr: pipeline_success_rate < 80
          for: 15m
          labels:
            severity: warning
            category: pipeline
          annotations:
            summary: Pipeline success rate below threshold
            description: The pipeline success rate has dropped below 80% in the last 15 minutes

        - alert: SecretDetected
          expr: secrets_detected_total > 0
          for: 1m
          labels:
            severity: critical
            category: security
          annotations:
            summary: Secrets detected in repository
            description: Gitleaks has detected potential secrets in the repository

        - alert: SlowDeployment
          expr: deployment_duration_seconds > 300
          for: 5m
          labels:
            severity: warning
            category: performance
          annotations:
            summary: Slow deployment detected
            description: Deployments are taking longer than 5 minutes to complete

      - name: InfrastructureAlerts
        rules:
        - alert: HighResourceUsage
          expr: container_memory_usage_bytes / container_spec_memory_limit_bytes * 100 > 90
          for: 10m
          labels:
            severity: warning
            category: infrastructure
          annotations:
            summary: High resource usage detected
            description: Container memory usage is above 90% for more than 10 minutes

        - alert: ArgocdSyncFailed
          expr: argocd_app_sync_status{status="Failed"} > 0
          for: 5m
          labels:
            severity: critical
            category: deployment
          annotations:
            summary: ArgoCD sync failure
            description: Application sync in ArgoCD has failed