apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: my-app
spec:
  selector:
    app: my-app  # Must match deployment's pod labels
  ports:
    - port: 80       # Service port
      targetPort: 8080  # Container port
      protocol: TCP
  type: ClusterIP  # Internal cluster access only
